- CHANGELOG.md
- Example/Podfile.lock
- MoEngagePluginBase.podspec
- MoEngagePluginBase/MoEngagePlugin.swift
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
Updated Initialization method with SDKState. Instead of passing bool for sdkState, now initialization method accepts parameter of type MoEngageSDKState
> MOEN-18794-PluginBase: Updated initialization method with sdkState

- MoEngagePluginCards/DataTransfer/NativeToHybrid/MoEngageCardData.swift
- MoEngagePluginCards/MoEngagePluginCardsBridge.swift
- Tests/MoEngagePluginCardsTests/MoEngagePluginCardsBridgeTest.swift
Native techdoc: https://moengagetrial.atlassian.net/wiki/spaces/MS/pages/3806986336/Sync+API+For+Cards
> MOEN-25537: expose fetchCards API to hybrid

- CHANGELOG.md
- Example/MoEPluginBaseExample/AppDelegate.m
- LICENSE
- MoEngagePluginBase.podspec
- MoEngagePluginBase/MoEngagePlugin.swift
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginBase/MoEngagePluginConstants.swift
- MoEngagePluginBase/MoEngagePluginUtils.swift
- MoEngagePluginCards.podspec
- MoEngagePluginCards/Helpers/MoEngageCardsPluginLogger.swift
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
> MOEN-30023: Updated to 9.16.0

- CHANGELOG.md
- Example/MoEPluginBaseExample/AppDelegate.m
- LICENSE
- MoEngagePluginBase.podspec
- MoEngagePluginBase/MoEngagePlugin.swift
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginBase/MoEngagePluginConstants.swift
- MoEngagePluginBase/MoEngagePluginUtils.swift
- MoEngagePluginCards.podspec
- MoEngagePluginCards/Helpers/MoEngageCardsPluginLogger.swift
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
* Updated to 9.16.0. Added Nudge support
* Updated pluginbase version
* Updated inapp dependency version
* MOEN-30675: Update version and changelog
---------
> MOEN-30023: Updated to 9.16.1 (#30)

- CHANGELOG.md
- MoEngagePluginBase.podspec
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginCards.podspec
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
* MOEN-30711: Added non-intrusive InApp support for tvOS
* MOEN-30711: Updated versions
> MOEN-30711: Added non-intrusive InApp support for tvOS (#32)

- MoEngagePluginBase/MoEngageAnalyticsConfig.swift
- MoEngagePluginBase/MoEngageHybridToNativeConfig.swift
- MoEngagePluginBase/MoEngageInitConfig.swift
- MoEngagePluginBase/MoEngageInitConfigCache.swift
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginBase/MoEngagePluginConstants.swift
- MoEngagePluginBase/MoEngagePluginUtils.swift
https://moengagetrial.atlassian.net/browse/MOEN-32294
Boolean User Attribute tracked as 0/1 instead of T/F fix.
> Boolean User Attribute tracked as 0/1 instead of T/F fix.

- CHANGELOG.md
- MoEngagePluginBase.podspec
- MoEngagePluginCards.podspec
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-33421
pinned ios version
> Moen 33421:  Pinned iOS version

- CHANGELOG.md
- MoEngagePluginCards/DataTransfer/NativeToHybrid/MoEngageCardSyncCompleteMetaData.swift
- MoEngagePluginCards/DataTransfer/Sync/MoEngageCardSyncManager.swift
- MoEngagePluginCards/MoEngagePluginCardsBridge.swift
https://moengagetrial.atlassian.net/browse/MOEN-33128
> MOEN-33128: Cards fetch on login

- CHANGELOG.md
- MoEngagePluginBase.podspec
- MoEngagePluginCards/Helpers/MoEngageCardsPluginLogger.swift
https://moengagetrial.atlassian.net/browse/MOEN-34072
updated plugin wrt latest native branch
> MOEN-34072: Updated Plugin wrt latest native branch

- CHANGELOG.md
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginBase/MoEngagePluginConstants.swift
- MoEngagePluginBase/MoEngagePluginParser.swift
- MoEngagePluginBase/MoEngagePluginUtils.swift
https://moengagetrial.atlassian.net/browse/MOEN-32219
Multiple selfhandled inapp support
> MOEN-32219: Multiple selfhandled inapp support

- CHANGELOG.md
- MoEngagePluginBase/MoEngagePluginBridge.swift
https://moengagetrial.atlassian.net/browse/MOEN-34381
Added support for provisional push
> MOEN-34381: Added support for provisional push

- CHANGELOG.md
- package.json
https://moengagetrial.atlassian.net/browse/MOEN-35351
Release - MoEngagePluginBase 5.1.1
> MOEN-35351: Release - MoEngagePluginBase 5.1.1

- CHANGELOG.md
- MoEngagePluginBase.podspec
- package.json
https://moengagetrial.atlassian.net/browse/MOEN-36493
Updated changelog and package.json
> Updated changelog and package.json

- CHANGELOG.md
- Example/Podfile
- MoEngagePluginBase.podspec
> MOEN-36385: Update native SDK

- CHANGELOG.md
- MoEngagePluginBase.podspec
- package.json
> MOEN-36845: Release Pluginbase 5.2.1

- CHANGELOG.md
- MoEngagePluginBase/MoEngagePluginUtils.swift
https://moengagetrial.atlassian.net/browse/MOEN-37590
> MOEN-37590: Always send key value pairs for inapp navigation payload

- .github/workflows/prepare-release.yml
> MOEN-36209: Update action actors

- CHANGELOG.md
- MoEngagePluginBase.podspec
- package.json
> MOEN-36209: Update versions to release Multi Id

- CHANGELOG.md
- Example/Podfile
- MoEngagePluginBase/MoEngageInitConfigCache.swift
- MoEngagePluginBase/MoEngagePluginBridge.swift
- Tests/MoEngagePluginBaseTests/ShouldTrackUserAttributeAsBooleanReadWriteTest.swift
- Tests/MoEngagePluginCardsTests/MoEngageCardSyncTest.swift
- Tests/MoEngagePluginCardsTests/MoEngagePluginCardsBridgeTest.swift
- Utilities/spec.rb
https://moengagetrial.atlassian.net/browse/MOEN-37628
Fixed ReadWrite synchronization to dictionary.
> MOEN-37628-Fixed ReadWrite synchronization

- CHANGELOG.md
- package.json
https://moengagetrial.atlassian.net/browse/MOEN-37814
updated package.json and changelog
> MOEN 37814 update package.json and changelog

- CHANGELOG.md
- Example/Podfile
- MoEngagePluginBase.podspec
- MoEngagePluginBase/MoEngageInitConfigCache.swift
- MoEngagePluginBase/MoEngagePluginBridge.swift
- MoEngagePluginCards.podspec
- Tests/MoEngagePluginBaseTests/ShouldTrackUserAttributeAsBooleanReadWriteTest.swift
https://moengagetrial.atlassian.net/browse/MOEN-37628
Fixed InitConfig data racing issue
> MOEN-37628-Fixed InitConfig data racing issue

- CHANGELOG.md
- MoEngagePluginBase.podspec
- MoEngagePluginCards.podspec
- MoEngagePluginGeofence.podspec
- MoEngagePluginInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-37814
Updated change Log
> MOEN-37814-UpdateChangeLog

- CHANGELOG.md
- MoEngagePluginBase.podspec
- package.json
https://moengagetrial.atlassian.net/browse/MOEN-37981
Update package version and change log
> Updated changelog and packageversion

- CHANGELOG.md
- MoEngagePluginInbox/MoEngagePluginInboxConstants.swift
- MoEngagePluginInbox/MoEngagePluginInboxUtils.swift
https://moengagetrial.atlassian.net/browse/MOEN-38387
Notification grouping and replacement
> MOEN-38387: Notification grouping and replacement

- CHANGELOG.md
- MoEngagePluginBase.podspec
- package.json
https://moengagetrial.atlassian.net/browse/MOEN-39261
Release Ticket: https://moengagetrial.atlassian.net/browse/REL-2069
Updated Package Version And ChangeLog for Release.
> MOEN 39261:  Update package version and change log

- MoEngagePluginCards/CHANGELOG.md
- package.json
> MOEN-39175: Changelog revert

- Example/MoEPluginBaseExample.xcodeproj/project.pbxproj
- Example/MoEPluginBaseExample/AppDelegate.m
- Example/MoEPluginBaseExample/MoEPluginBaseExample-Info.plist
- Example/MoEPluginBaseExample/MoEPluginBaseExample.entitlements
- MoEngagePluginBase/CHANGELOG.md
- MoEngagePluginBase/MoEngagePlugin.swift
- MoEngagePluginBase/MoEngageSDKDefaultInitializationConfig.swift
- MoEngagePluginCards/CHANGELOG.md
- MoEngagePluginCards/Helpers/MoEngageCardsPluginLogger.swift
- MoEngagePluginGeofence/CHANGELOG.md
- MoEngagePluginInbox/CHANGELOG.md
> MOEN-38662: Added file based initialization support
